-- Genera DROP I_SNP_LSCHEMA
set serveroutput on

BEGIN
    DBMS_OUTPUT.NEW_LINE;
    DBMS_OUTPUT.PUT_LINE('Inicio: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));


    EXECUTE IMMEDIATE 'DROP TABLE I_SNP_LSCHEMA CASCADE CONSTRAINTS PURGE';

    DBMS_OUTPUT.PUT_LINE('Proceso ABORT_REDEF SNP_LSCHEMA : OK');
    DBMS_OUTPUT.PUT_LINE('Finalización: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));
    DBMS_OUTPUT.NEW_LINE;



EXCEPTION
   WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('Proceso ABORT_REDEF SNP_LSCHEMA  con error: '||SQLERRM);
	DBMS_OUTPUT.PUT_LINE('Finalización: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));
    DBMS_OUTPUT.NEW_LINE;
END;
/
EXIT