CREATE UNIQUE INDEX DEV_ODI_REPO.TP_AK_LSCHEMA ON DEV_ODI_REPO.TABLA_PRUEBA
(LSCHEMA_NAME)
LOGGING
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
PCTINCREASE      0
BUFFER_POOL      DEFAULT
)
NOPARALLEL;


CREATE UNIQUE INDEX DEV_ODI_REPO.TP_AK_LSCHEMA_GUID ON DEV_ODI_REPO.TABLA_PRUEBA
(GLOBAL_ID)
LOGGING
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
PCTINCREASE      0
BUFFER_POOL      DEFAULT
)
NOPARALLEL;


CREATE INDEX DEV_ODI_REPO.TP_IDX_LSCHEMA_LD ON DEV_ODI_REPO.TABLA_PRUEBA
(LAST_DATE)
LOGGING
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
PCTINCREASE      0
BUFFER_POOL      DEFAULT
)
NOPARALLEL;


CREATE INDEX DEV_ODI_REPO.TP_LSCHEMA_FK1 ON DEV_ODI_REPO.TABLA_PRUEBA
(I_TECHNO)
LOGGING
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
PCTINCREASE      0
BUFFER_POOL      DEFAULT
)
NOPARALLEL;


CREATE INDEX DEV_ODI_REPO.TP_LSCHEMA_FK2 ON DEV_ODI_REPO.TABLA_PRUEBA
(I_TGT_DB_LS)
LOGGING
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
PCTINCREASE      0
BUFFER_POOL      DEFAULT
)
NOPARALLEL;


CREATE UNIQUE INDEX DEV_ODI_REPO.TP_PK_LSCHEMA ON DEV_ODI_REPO.TABLA_PRUEBA
(I_LSCHEMA)
LOGGING
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
PCTINCREASE      0
BUFFER_POOL      DEFAULT
)
NOPARALLEL;


