-- Genera CAN_REDEF  TABLA_PRUEBA
set serveroutput on

BEGIN
   DBMS_OUTPUT.NEW_LINE;
   DBMS_OUTPUT.PUT_LINE('Inicio: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));


  DBMS_REDEFINITION.CAN_REDEF_TABLE(
  				uname => 'DEV_ODI_REPO',
				tname => 'TABLA_PRUEBA',
				options_flag  => DBMS_REDEFINITION.CONS_USE_ROWID
				);

  DBMS_OUTPUT.PUT_LINE('Proceso CAN_REDEF  TABLA_PRUEBA : OK');
  DBMS_OUTPUT.PUT_LINE('Finalización: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));
  DBMS_OUTPUT.NEW_LINE;


EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Proceso CAN_REDEF TABLA_PRUEBA con error '||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Finalización: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));
        DBMS_OUTPUT.NEW_LINE;

END;
/
EXIT