
  CREATE TABLE DEV_ODI_REPO.I_TABLA_PRUEBA 
   (  I_LSCHEMA NUMBER(19,0), 
  I_TECHNO NUMBER(19,0), 
  LSCHEMA_NAME VARCHAR2(35 CHAR) ENCRYPT USING 'AES256' NO SALT , 
  IND_CHANGE VARCHAR2(1 CHAR), 
  EXT_VERSION VARCHAR2(35 CHAR) ENCRYPT USING 'AES256' NO SALT , 
  LAST_USER VARCHAR2(400 CHAR), 
  FIRST_DATE DATE, 
  FIRST_USER VARCHAR2(400 CHAR), 
  LAST_DATE DATE, 
  INT_VERSION NUMBER(19,0), 
  GLOBAL_ID VARCHAR2(36 CHAR), 
  PROCESS_TYPE VARCHAR2(1 CHAR), 
  I_TGT_DB_LS NUMBER(19,0) ENCRYPT USING 'AES256' NO SALT 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 ROW STORE COMPRESS ADVANCED LOGGING
  TABLESPACE USERS ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.I_LSCHEMA IS 'Este campo es un identificador del esquema' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.I_TECHNO IS 'Este campo es un identificador de la Tecnología' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.LSCHEMA_NAME IS 'Nombre del esquema logico' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.IND_CHANGE IS 'Flag que indica el cambio' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.EXT_VERSION IS 'Version Externa' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.LAST_USER IS 'El último usuario que ejecuto' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.FIRST_DATE IS 'La primera vez que se ejecuto' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.FIRST_USER IS 'El primer usuario en ejecutar' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.LAST_DATE IS 'Ultima fecha de ejecución' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.INT_VERSION IS 'Version Interna' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.GLOBAL_ID IS 'Identificador Global' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.PROCESS_TYPE IS 'Flag del tipo de proceso' ;
COMMENT ON COLUMN DEV_ODI_REPO.I_TABLA_PRUEBA.I_TGT_DB_LS IS 'Identifiacdor del Esquema Logico en la base Target' ;
EXIT