-- Genera FINISH REDEFINITION TABLA_PRUEBA
set serveroutput on

BEGIN
        DBMS_OUTPUT.NEW_LINE;
        DBMS_OUTPUT.PUT_LINE('Inicio: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));

        DBMS_REDEFINITION.FINISH_REDEF_TABLE(
					      uname      => 'DEV_ODI_REPO' , 
					      orig_table => 'TABLA_PRUEBA' , 
					      int_table  => 'I_TABLA_PRUEBA'
					    );

        DBMS_OUTPUT.PUT_LINE('Proceso FINISH TABLA_PRUEBA : OK');
        DBMS_OUTPUT.PUT_LINE('Finalización: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));
        DBMS_OUTPUT.NEW_LINE;
        
        FOR INDICE IN (SELECT INDEX_NAME FROM ALL_INDEXES 
                       WHERE TABLE_NAME='TABLA_PRUEBA' AND OWNER='DEV_ODI_REPO')
        LOOP
                EXECUTE IMMEDIATE('ALTER INDEX DEV_ODI_REPO.INDICE NOPARALLEL') ;
        END LOOP;        

EXCEPTION
    when OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Proceso FINISH TABLA_PRUEBA con error: '||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Finalización: ' || TO_CHAR(SYSDATE,'YYYY/MM/DD  HH24:MI:SS'));
        DBMS_OUTPUT.NEW_LINE;

END;
/
EXIT