  ALTER SESSION FORCE PARALLEL DML parallel 4;
  ALTER SESSION FORCE PARALLEL DDL parallel 4;
  ALTER SESSION FORCE PARALLEL QUERY parallel 4;

  CREATE UNIQUE INDEX DEV_ODI_REPO.I_TP_AK_LSCHEMA ON DEV_ODI_REPO.I_TABLA_PRUEBA (LSCHEMA_NAME) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_PRUEBA  ;
  CREATE UNIQUE INDEX DEV_ODI_REPO.I_TP_PK_LSCHEMA ON DEV_ODI_REPO.I_TABLA_PRUEBA (I_LSCHEMA) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_PRUEBA  ;
  CREATE UNIQUE INDEX DEV_ODI_REPO.I_TP_AK_LSCHEMA_GUID ON DEV_ODI_REPO.I_TABLA_PRUEBA (GLOBAL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_PRUEBA  ;
  CREATE INDEX DEV_ODI_REPO.I_TP_LSCHEMA_FK1 ON DEV_ODI_REPO.I_TABLA_PRUEBA (I_TECHNO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_PRUEBA  ;
  CREATE INDEX DEV_ODI_REPO.I_TP_LSCHEMA_FK2 ON DEV_ODI_REPO.I_TABLA_PRUEBA (I_TGT_DB_LS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_PRUEBA  ;
  CREATE INDEX DEV_ODI_REPO.I_TP_IDX_LSCHEMA_LD ON DEV_ODI_REPO.I_TABLA_PRUEBA (LAST_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_PRUEBA  ;
  EXIT