
  CREATE TABLE DEV_ODI_REPO.I_SNP_LSCHEMA 
   (  I_LSCHEMA NUMBER(19,0), 
  I_TECHNO NUMBER(19,0), 
  LSCHEMA_NAME VARCHAR2(35 CHAR), 
  IND_CHANGE VARCHAR2(1 CHAR), 
  EXT_VERSION VARCHAR2(35 CHAR), 
  LAST_USER VARCHAR2(400 CHAR), 
  FIRST_DATE DATE, 
  FIRST_USER VARCHAR2(400 CHAR), 
  LAST_DATE DATE, 
  INT_VERSION NUMBER(19,0), 
  GLOBAL_ID VARCHAR2(36 CHAR), 
  PROCESS_TYPE VARCHAR2(1 CHAR), 
  I_TGT_DB_LS NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 ROW STORE COMPRESS ADVANCED LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE TS_MOMER ;
EXIT