  ALTER SESSION FORCE PARALLEL DML parallel 16;
  ALTER SESSION FORCE PARALLEL DDL parallel 16;
  ALTER SESSION FORCE PARALLEL QUERY parallel 16;

  CREATE INDEX DEV_ODI_REPO.I_LSCHEMA_FK2 ON DEV_ODI_REPO.I_SNP_LSCHEMA (I_TGT_DB_LS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_BDOR  ;
  CREATE UNIQUE INDEX DEV_ODI_REPO.I_PK_LSCHEMA ON DEV_ODI_REPO.I_SNP_LSCHEMA (I_LSCHEMA) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_BDOR  ;
  CREATE UNIQUE INDEX DEV_ODI_REPO.I_AK_LSCHEMA ON DEV_ODI_REPO.I_SNP_LSCHEMA (LSCHEMA_NAME) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_BDOR  ;
  CREATE UNIQUE INDEX DEV_ODI_REPO.I_AK_LSCHEMA_GUID ON DEV_ODI_REPO.I_SNP_LSCHEMA (GLOBAL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_BDOR  ;
  CREATE INDEX DEV_ODI_REPO.I_IDX_LSCHEMA_LD ON DEV_ODI_REPO.I_SNP_LSCHEMA (LAST_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_BDOR  ;
  CREATE INDEX DEV_ODI_REPO.I_LSCHEMA_FK1 ON DEV_ODI_REPO.I_SNP_LSCHEMA (I_TECHNO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  COMPRESS ADVANCED LOW 
  TABLESPACE TS_BDOR  ;
  EXIT