CREATE TABLE "DEV_ODI_REPO.SNP_LSCHEMA"
(
  I_LSCHEMA     NUMBER(19),
  I_TECHNO      NUMBER(19),
  LSCHEMA_NAME  VARCHAR2(35 CHAR),
  IND_CHANGE    VARCHAR2(1 CHAR),
  EXT_VERSION   VARCHAR2(35 CHAR),
  LAST_USER     VARCHAR2(400 CHAR),
  FIRST_DATE    DATE,
  FIRST_USER    VARCHAR2(400 CHAR),
  LAST_DATE     DATE,
  INT_VERSION   NUMBER(19),
  GLOBAL_ID     VARCHAR2(36 CHAR),
  PROCESS_TYPE  VARCHAR2(1 CHAR),
  I_TGT_DB_LS   NUMBER(19)
)
TABLESPACE DEV_ODI_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX "DEV_ODI_REPO.AK_LSCHEMA" ON "DEV_ODI_REPO.SNP_LSCHEMA"
(LSCHEMA_NAME)
TABLESPACE "DEV_ODI_USER"
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX DEV_ODI_REPO.AK_LSCHEMA_GUID ON DEV_ODI_REPO.SNP_LSCHEMA
(GLOBAL_ID)
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX DEV_ODI_REPO.IDX_LSCHEMA_LD ON DEV_ODI_REPO.SNP_LSCHEMA
(LAST_DATE)
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX DEV_ODI_REPO.LSCHEMA_FK1 ON DEV_ODI_REPO.SNP_LSCHEMA
(I_TECHNO)
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX DEV_ODI_REPO.LSCHEMA_FK2 ON DEV_ODI_REPO.SNP_LSCHEMA
(I_TGT_DB_LS)
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX DEV_ODI_REPO.PK_LSCHEMA ON DEV_ODI_REPO.SNP_LSCHEMA
(I_LSCHEMA)
TABLESPACE DEV_ODI_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
